services:
  - mongodb

language: node_js

node_js:
  - "4.4.7"

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update
  - sudo apt-get -qq install g++-4.8
  - curl https://install.meteor.com | /bin/sh
  - export PATH="$HOME/.meteor:$PATH"

cache:
  directories:
    - node_modules

before_script:
  - meteor npm install

script:
  - meteor add dispatch:mocha-phantomjs
  - meteor test --once --driver-package dispatch:mocha-phantomjs
  - meteor build $HOME/build.tgz
  
env:
  - CXX=g++-4.8
